### ISSUE TITLE
Split toolkit into multiple packages

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/Rapid-XAML-Toolkit#206]
With this toolkit containing, potentially, many different tools that may not be wanted or needed by everyone, how should they be packaged so that we balance:
- Making new functionality available to people with the toolkit already installed.
- Not forcing all functionality on everyone.
- Making it easy to manage the project and not end up with lots of separate installable elements to administer.

The simple solution is to "make everything configurable within a single installer." 
The problem with this is that some extensibility points do not offer a way to control their exposure.

The options are:
- Multiple separate VSIX files. (With an extension package to make installing them all, and being informed about new functionality, easier.)
- Single VSIX with configuration for as much as possible.

**Comment by mrlacey** [comment]
all in one vsix

for now. can split anything in the future if necessary

**Comment by kmgallahan** [comment]
I would suggest that the toolkit be split into:

* A "Rapid XAML Generation" component
* A "Microsoft.xaml.analyzers" style component

I imagine the audience for analyzers is broader than that of code generation, but could be wrong. 

This split would help discoverability of the analyzers (I wasn't even aware they were in here until re-visiting the repo today).

**Comment by mrlacey** [comment]
@kmgallahan thanks for the feedback.
Unfortunately it's not (yet--hopefully) possible to package XAML analyzers in the same way as Roslyn analyzers. For this reason everything is still in a single package. Currently everything is in a single VSIX as this made more sense than having multiple VSIX packages that wouldn't necessarily be any more discoverable.

I know that awareness and promotion is still currently low but as we get nearer to a v1.0 release this will change.

**Comment by mrlacey** [comment]
Reopening as external circumstances may make this desirable.
Being open it makes it easier to find and cross-reference ;)

**Comment by mrlacey** [comment]
This is happening!

The functionality will be available in separate VSIX packages so it will be possible to install only what's wanted.
There will also be an "extension pack" available which will enable the installing of everything at once.

Initially, there will be 2 separate install options (Generation & Analysis) but this will grow in time.

**Comment by mrlacey** [comment]
Still to do

- [x] fix project type references in the options dialog
- [x] verify all functionality.
- [x] update contributing and testing docs
- [x] turn the original project to be an extension pack.
- [x] add blue border icon to extension pack
- [x] update version numbering
- [x] update options emulator
- [x] update test project references
- [x] update manual test projects

**Comment by mrlacey** [comment]
investigating marketplace distro/indexing issue before publishing

**Comment by mrlacey** [comment]
Move menu definitions from the extension pack and create as a separate library (RX.Common ?) referenced by those that need is.
