### ISSUE TITLE
Support localization of VSIX

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/Rapid-XAML-Toolkit#312]
Due to an inability to fund localization, partially localized content was removed in 

It would be great to enable this again
- [ ] Once the code-base is stable
- [ ] Once time and resources allow
- [ ] After reviewing how to determine what to localize. (e.g. Not sure if localizing all output messages is helpful. Should only direct UI elements be localized?)
