### ISSUE TITLE
Refactor and restructure resource files

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/Rapid-XAML-Toolkit#314]
As a result of restructuring into multiple projects/extensions need to do the following related to resource files.

- [x] Ensure using an appropriate structure for moving forward
- [x] Ensure consistencies in naming
- [x] Update localization tool (as appropriate)
- [x] Update [localization docs](https://github.com/mrlacey/Rapid-XAML-Toolkit/blob/master/docs/localization.md)
